# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/v1/ai.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ai/v1/ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61i/v1/ai.proto\x12\x05\x61i.v1\"2\n\x0b\x43hatRequest\x12\x13\n\x0btelegram_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\"5\n\x0c\x43hatResponse\x12\x13\n\x0btelegram_id\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t2<\n\tAIService\x12/\n\x04\x43hat\x12\x12.ai.v1.ChatRequest\x1a\x13.ai.v1.ChatResponseB Z\x1erageai/proto/gen/go/ai/v1;aiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.v1.ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036rageai/proto/gen/go/ai/v1;aiv1'
  _globals['_CHATREQUEST']._serialized_start=25
  _globals['_CHATREQUEST']._serialized_end=75
  _globals['_CHATRESPONSE']._serialized_start=77
  _globals['_CHATRESPONSE']._serialized_end=130
  _globals['_AISERVICE']._serialized_start=132
  _globals['_AISERVICE']._serialized_end=192
# @@protoc_insertion_point(module_scope)
