# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rpc.ai.v1 import ai_pb2 as ai_dot_v1_dot_ai__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai/v1/ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/ai.v1.AIService/Chat',
                request_serializer=ai_dot_v1_dot_ai__pb2.ChatRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.AnalyzeProfile = channel.unary_unary(
                '/ai.v1.AIService/AnalyzeProfile',
                request_serializer=ai_dot_v1_dot_ai__pb2.AnalyzeProfileRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.AnalyzeProfileResponse.FromString,
                _registered_method=True)
        self.GetChatHistory = channel.unary_unary(
                '/ai.v1.AIService/GetChatHistory',
                request_serializer=ai_dot_v1_dot_ai__pb2.GetChatHistoryRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.GetChatHistoryResponse.FromString,
                _registered_method=True)
        self.ClearChatHistory = channel.unary_unary(
                '/ai.v1.AIService/ClearChatHistory',
                request_serializer=ai_dot_v1_dot_ai__pb2.ClearChatHistoryRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.ClearChatHistoryResponse.FromString,
                _registered_method=True)
        self.ListChatSessions = channel.unary_unary(
                '/ai.v1.AIService/ListChatSessions',
                request_serializer=ai_dot_v1_dot_ai__pb2.ListChatSessionsRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.ListChatSessionsResponse.FromString,
                _registered_method=True)
        self.GetProfileRoastHistory = channel.unary_unary(
                '/ai.v1.AIService/GetProfileRoastHistory',
                request_serializer=ai_dot_v1_dot_ai__pb2.GetProfileRoastHistoryRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.GetProfileRoastHistoryResponse.FromString,
                _registered_method=True)
        self.ClearProfileRoastHistory = channel.unary_unary(
                '/ai.v1.AIService/ClearProfileRoastHistory',
                request_serializer=ai_dot_v1_dot_ai__pb2.ClearProfileRoastHistoryRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.ClearProfileRoastHistoryResponse.FromString,
                _registered_method=True)
        self.ListProfileRoastSessions = channel.unary_unary(
                '/ai.v1.AIService/ListProfileRoastSessions',
                request_serializer=ai_dot_v1_dot_ai__pb2.ListProfileRoastSessionsRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.ListProfileRoastSessionsResponse.FromString,
                _registered_method=True)
        self.GetLLMConfig = channel.unary_unary(
                '/ai.v1.AIService/GetLLMConfig',
                request_serializer=ai_dot_v1_dot_ai__pb2.GetLLMConfigRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.GetLLMConfigResponse.FromString,
                _registered_method=True)
        self.GetSystemPrompt = channel.unary_unary(
                '/ai.v1.AIService/GetSystemPrompt',
                request_serializer=ai_dot_v1_dot_ai__pb2.GetSystemPromptRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.GetSystemPromptResponse.FromString,
                _registered_method=True)
        self.UpdateSystemPrompt = channel.unary_unary(
                '/ai.v1.AIService/UpdateSystemPrompt',
                request_serializer=ai_dot_v1_dot_ai__pb2.UpdateSystemPromptRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.UpdateSystemPromptResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ai.v1.AIService/Health',
                request_serializer=ai_dot_v1_dot_ai__pb2.HealthRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.HealthResponse.FromString,
                _registered_method=True)


class AIServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearChatHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChatSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileRoastHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearProfileRoastHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProfileRoastSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLLMConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSystemPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.ChatRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.ChatResponse.SerializeToString,
            ),
            'AnalyzeProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeProfile,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.AnalyzeProfileRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.AnalyzeProfileResponse.SerializeToString,
            ),
            'GetChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatHistory,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.GetChatHistoryRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.GetChatHistoryResponse.SerializeToString,
            ),
            'ClearChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearChatHistory,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.ClearChatHistoryRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.ClearChatHistoryResponse.SerializeToString,
            ),
            'ListChatSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChatSessions,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.ListChatSessionsRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.ListChatSessionsResponse.SerializeToString,
            ),
            'GetProfileRoastHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileRoastHistory,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.GetProfileRoastHistoryRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.GetProfileRoastHistoryResponse.SerializeToString,
            ),
            'ClearProfileRoastHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearProfileRoastHistory,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.ClearProfileRoastHistoryRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.ClearProfileRoastHistoryResponse.SerializeToString,
            ),
            'ListProfileRoastSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProfileRoastSessions,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.ListProfileRoastSessionsRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.ListProfileRoastSessionsResponse.SerializeToString,
            ),
            'GetLLMConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLLMConfig,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.GetLLMConfigRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.GetLLMConfigResponse.SerializeToString,
            ),
            'GetSystemPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemPrompt,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.GetSystemPromptRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.GetSystemPromptResponse.SerializeToString,
            ),
            'UpdateSystemPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSystemPrompt,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.UpdateSystemPromptRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.UpdateSystemPromptResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.HealthRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.v1.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.v1.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIService/Chat',
            ai_dot_v1_dot_ai__pb2.ChatRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIService/AnalyzeProfile',
            ai_dot_v1_dot_ai__pb2.AnalyzeProfileRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.AnalyzeProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIService/GetChatHistory',
            ai_dot_v1_dot_ai__pb2.GetChatHistoryRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.GetChatHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIService/ClearChatHistory',
            ai_dot_v1_dot_ai__pb2.ClearChatHistoryRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.ClearChatHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChatSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIService/ListChatSessions',
            ai_dot_v1_dot_ai__pb2.ListChatSessionsRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.ListChatSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfileRoastHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIService/GetProfileRoastHistory',
            ai_dot_v1_dot_ai__pb2.GetProfileRoastHistoryRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.GetProfileRoastHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearProfileRoastHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIService/ClearProfileRoastHistory',
            ai_dot_v1_dot_ai__pb2.ClearProfileRoastHistoryRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.ClearProfileRoastHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProfileRoastSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIService/ListProfileRoastSessions',
            ai_dot_v1_dot_ai__pb2.ListProfileRoastSessionsRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.ListProfileRoastSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLLMConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIService/GetLLMConfig',
            ai_dot_v1_dot_ai__pb2.GetLLMConfigRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.GetLLMConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIService/GetSystemPrompt',
            ai_dot_v1_dot_ai__pb2.GetSystemPromptRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.GetSystemPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSystemPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIService/UpdateSystemPrompt',
            ai_dot_v1_dot_ai__pb2.UpdateSystemPromptRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.UpdateSystemPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIService/Health',
            ai_dot_v1_dot_ai__pb2.HealthRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
